#!/bin/sh

if [ -L "${XDG_CONFIG_HOME}/vim/vimrc" ]; then
    mkdir -p "${XDG_CACHE_HOME}/vim/backup"
    mkdir -p "${XDG_CACHE_HOME}/vim/swap"
    mkdir -p "${XDG_CACHE_HOME}/vim/undo"

    if [ -d "${XDG_CONFIG_HOME}/vim" -a ! -d "${XDG_CONFIG_HOME}/vim/bundle" ]; then
        echo "Installing vim plugins..."
        vim -E -s -u "${XDG_CONFIG_HOME}/vim/vimrc" +PlugInstall +qall
        # Trigger black install
        vim -E -s -u "${XDG_CONFIG_HOME}/vim/vimrc" +qall

        if [ ! -n "$(type flake8 2>/dev/null)" ]; then
            echo "Reminder: install flake8"
        fi
        if [ ! -n "$(type shellcheck 2>/dev/null)" ]; then
            echo "Reminder: install shellcheck"
        fi
    fi
fi
